#!/usr/bin/env node
/**
 * Converts a book cover image into:
 * 1. An SVG for preview
 * 2. A TS module with rects in BFS reveal order for the canvas
 *
 * Usage: node scripts/cover-to-svg.mjs <input-image> <name>
 * Example: node scripts/cover-to-svg.mjs public/notes-from-underground.png notes-from-underground
 */

import sharp from "sharp";
import { writeFileSync } from "fs";

const input = process.argv[2];
const name = process.argv[3];

if (!input || !name) {
  console.error("Usage: node scripts/cover-to-svg.mjs <image> <name> [density] [cutoff]");
  console.error("Example: node scripts/cover-to-svg.mjs public/cover.png my-book 0.35 220");
  console.error("  density: 0-1, lower = sparser (default 0.35)");
  console.error("  cutoff:  0-255, lower = only darkest areas (default 220)");
  process.exit(1);
}

// --- Config (mirrors CursorTrail drawing params) ---
const TARGET_WIDTH = 400;
const MAX_DENSITY = parseFloat(process.argv[4] || "0.35");
const CUTOFF = parseInt(process.argv[5] || "220");

// --- Load & prepare image ---
const { data, info } = await sharp(input)
  .flatten({ background: "#ffffff" }) // transparent → white
  .resize(TARGET_WIDTH)
  .grayscale()
  .normalize()
  .blur(1.2)
  .raw()
  .toBuffer({ resolveWithObject: true });

const w = info.width;
const h = info.height;

// Seeded PRNG for reproducible output
let seed = 42;
function rand() {
  seed = (seed * 16807 + 0) % 2147483647;
  return (seed - 1) / 2147483646;
}

// --- Generate rects ---
const rects = [];

for (let y = 0; y < h; y++) {
  for (let x = 0; x < w; x++) {
    const brightness = data[y * w + x];
    if (brightness > CUTOFF) continue;
    const darkness = 1 - brightness / 255;
    if (rand() > darkness * MAX_DENSITY) continue;

    rects.push({
      x: +(x + (rand() - 0.5) * 4).toFixed(1),
      y: +(y + (rand() - 0.5) * 4).toFixed(1),
      w: +(rand() * 2.5 + 1).toFixed(1),
      h: +(rand() * 2.5 + 1).toFixed(1),
      o: +(0.5 + rand() * 0.2).toFixed(2),
    });
  }
}

// --- BFS reveal order (same logic as CursorTrail spatialRevealOrder) ---
const cellSize = 6;
const grid = new Map();
for (let i = 0; i < rects.length; i++) {
  const key = `${Math.floor(rects[i].x / cellSize)},${Math.floor(rects[i].y / cellSize)}`;
  if (!grid.has(key)) grid.set(key, []);
  grid.get(key).push(i);
}

// Start from bottom-center
let minX = Infinity, maxX = -Infinity, maxY = -Infinity;
for (const r of rects) {
  if (r.x < minX) minX = r.x;
  if (r.x > maxX) maxX = r.x;
  if (r.y > maxY) maxY = r.y;
}
let startIdx = 0, minDist = Infinity;
const seedX = (minX + maxX) / 2, seedY = maxY;
for (let i = 0; i < rects.length; i++) {
  const d = (rects[i].x - seedX) ** 2 + (rects[i].y - seedY) ** 2;
  if (d < minDist) { minDist = d; startIdx = i; }
}

const visited = new Set();
const order = [];

function bfsFrom(start) {
  const queue = [start];
  visited.add(start);
  while (queue.length > 0) {
    const idx = queue.shift();
    order.push(idx);
    const gx = Math.floor(rects[idx].x / cellSize);
    const gy = Math.floor(rects[idx].y / cellSize);
    const nearby = [];
    for (let dx = -3; dx <= 3; dx++) {
      for (let dy = -3; dy <= 3; dy++) {
        const cell = grid.get(`${gx + dx},${gy + dy}`);
        if (cell) for (const ni of cell) if (!visited.has(ni)) nearby.push(ni);
      }
    }
    nearby.sort((a, b) => {
      const da = (rects[a].x - rects[idx].x) ** 2 + (rects[a].y - rects[idx].y) ** 2;
      const db = (rects[b].x - rects[idx].x) ** 2 + (rects[b].y - rects[idx].y) ** 2;
      return da - db;
    });
    for (const ni of nearby) {
      if (!visited.has(ni)) { visited.add(ni); queue.push(ni); }
    }
  }
}

bfsFrom(startIdx);
while (order.length < rects.length) {
  const last = rects[order[order.length - 1]];
  let bestIdx = -1, bestDist = Infinity;
  for (let i = 0; i < rects.length; i++) {
    if (visited.has(i)) continue;
    const d = (rects[i].x - last.x) ** 2 + (rects[i].y - last.y) ** 2;
    if (d < bestDist) { bestDist = d; bestIdx = i; }
  }
  if (bestIdx === -1) break;
  bfsFrom(bestIdx);
}

const ordered = order.map(i => rects[i]);

// --- Write SVG (for preview) ---
const svgRects = ordered.map(r =>
  `<rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" opacity="${r.o}"/>`
);
const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" width="${w}" height="${h}" fill="#2a2a2a">\n${svgRects.join("\n")}\n</svg>`;
writeFileSync(`public/${name}.svg`, svg);

// --- Write TS module (for canvas) ---
// Compact format: [x, y, w, h, opacity] tuples
const tuples = ordered.map(r => `[${r.x},${r.y},${r.w},${r.h},${r.o}]`);
const ts = `// Auto-generated by scripts/cover-to-svg.mjs — do not edit
// Source dimensions: ${w}x${h}
export const width = ${w};
export const height = ${h};
export const rects: [number, number, number, number, number][] = [\n${tuples.join(",\n")}\n];\n`;
writeFileSync(`src/covers/${name}.ts`, ts);

console.log(`${ordered.length} rects (BFS ordered)`);
console.log(`  SVG: public/${name}.svg`);
console.log(`  TS:  src/covers/${name}.ts`);
